export const ADD_COMMENT = 'ADD_COMMENT';
export const BOOKS_LOADING = 'BOOKS_LOADING';
export const BOOKS_FAILED = 'BOOKS_FAILED';
export const ADD_BOOKS = 'ADD_BOOKS';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';